$ANSIBLE_VAULT;1.1;AES256
65306333633630386336303362653230306531383235653535376530323237333533653834633239
3135626563383362343535333232613765313333626566300a343438353662333234653762353137
33333663646365336439363738303935306662623263613361656230343532656434343237353135
3765653636376533320a333164643130333437353363393066316262366462346265353431353935
39306536643437333465363430653837376635363133333333353361396133333563336364653735
63383235333535653161666236386634366232383538643836393965633463376334666632613965
38396230306132663664343464653836313730376231306439636330313237633931383964646233
61336335343539353162383037303536396334623532396439356137343131653139373764386231
32346465643363343665653261663465363165373038313232306133386162366333363365666535
31363464353463356261343836316366393566613239313564626433353035376136303930313230
30326534396266346433323139623765623337386437313664366466666661636362323536313363
37373332613333356665316431366532653463653939343736633439653761316161356463376333
32636362363561653335633263653636636333613431663862646464356361633032
